import { Outfit } from 'next/font/google';
import './globals.css';
import { ClerkProvider, GoogleOneTap } from '@clerk/nextjs';

const inter = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider>
        <GoogleOneTap />
        <body className={inter.className}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
